### ISSUE TITLE
not compiling in visual studio 

### ISSUE THREAD

**Issue by khanzzirfan** [RocKhalil/Freelancer-Template#1]
Hi, 
Project is not even compiling in visual studio. Can you please include all the solution file.
Am I missing any dependency's for this project that I need to download externally?

**Comment by RocKhalil** [comment]
Hello,

All the files are included and should compile perfectly;

Can you please take a screenshot of the error ?

**Comment by khanzzirfan** [comment]
Hi,
I cannot see visual studio solution file after downloading the project. I created a empty web project and then included all the files from download and compiled the project. 

![image](https://cloud.githubusercontent.com/assets/8625166/12076062/b22c1028-b1ff-11e5-9951-651d0b3f1784.png)

**Comment by RocKhalil** [comment]
Try the following:

File -> Open Website

![image](https://cloud.githubusercontent.com/assets/5897339/12076074/04d523fc-b1a4-11e5-96dd-17b5c968671c.png)

Choose the file

Try to compile;

It should work fine.

**Comment by khanzzirfan** [comment]
Hi,
That worked for me (open as web site). Thank you for your help.
Also, Update read me file, so that users know they have to change the localfile path.
