### ISSUE TITLE
cannot send email through 'Contact me' Section

### ISSUE THREAD

**Issue by nsniteshsahni** [RocKhalil/Freelancer-Template#2]
Hi there,
I can't send email through 'contact me' section. I have changed the attribute 'MyEmail' to my email address in web.config file but still after clicking submit button, it says "Sorry, it seems that mail server is not responding. Please try again later!". Please suggest a solution.

Thank you in advance!!

**Comment by RocKhalil** [comment]
Hello,
You'll need to configure the SMTP in the web.config or in the util.cs;

Once fixed, it will start working fine.

Regards,

**Comment by nsniteshsahni** [comment]
Thank you very much for your assistance, I have already figured that out
Cheers!!
